version: "3.8"
services:
  app:
    build: .
    container_name: single-dev
    ports:
      - "5173:5173"
      - "3000:3000"
      - "443:443"
    env_file: .env
    environment:
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./:/workspace:cached 
      - ./nginx/app.conf:/etc/nginx/conf.d/app.conf:ro
      - ./backend:/app/backend
      - /app/backend/node_modules
      - ./frontend:/app/frontend
      - /app/frontend/node_modules
      - ./cloudflared:/app/cloudflared
      - mongo-data:/data/db
volumes:
  mongo-data:
